### ISSUE TITLE
 运行sh GestureKNN.sh的时候cuda报错

### ISSUE THREAD

**Issue by binwangnetmind** [YoungSeng/QPGesture#3]
Traceback (most recent call last):
  File "GestureKNN.py", line 859, in <module>
    main_codebook(maxFrames=args.max_frames)
  File "GestureKNN.py", line 825, in main_codebook
    args.train_database, args.train_codebook, args.test_data, args.train_wavlm, args.test_wavlm, args.train_wavvq, args.test_wavvq)
  File "/home/bin.wang/QPGesture/codebook/Speech2GestureMatching/data_processing.py", line 339, in load_db_codebook
    train_phase = np.load(data_file, allow_pickle=True)['phase']       # n, len, 4 (1 * 8 * 1)
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/numpy/lib/npyio.py", line 256, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/numpy/lib/format.py", line 748, in read_array
    array = pickle.load(fp, **pickle_kwargs)
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/torch/storage.py", line 240, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/torch/serialization.py", line 1012, in _legacy_load
    result = unpickler.load()
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/torch/serialization.py", line 958, in persistent_load
    wrap_storage=restore_location(obj, location),
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/torch/serialization.py", line 215, in default_restore_location
    result = fn(storage, location)
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/torch/serialization.py", line 182, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/bin.wang/miniconda3/envs/gesture/lib/python3.7/site-packages/torch/serialization.py", line 173, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 3 but torch.cuda.device_count() is 2. Please use torch.load with map_location to map your storages to an existing device.

**Comment by YoungSeng** [comment]
感谢你的反馈，已经完善，见issue https://github.com/YoungSeng/QPGesture/issues/2#issuecomment-1575510768
