### ISSUE TITLE
AssertionError: Invalid device id

### ISSUE THREAD

**Issue by hmthanh** [YoungSeng/QPGesture#6]
In inference code, I run following command:
```bash
python VisualizeCodebook.py \
  --config=./configs/codebook.yml \
  --no_cuda 1 \
  --gpu 0 \
  --code_path "./Speech2GestureMatching/output/result.npz" \
  --VQVAE_model_path "../../pretrained_model/codebook_checkpoint_best.bin" \
  --stage inference
```

Error message:

```
Traceback (most recent call last):
  File "/kaggle/working/codebook/VisualizeCodebook.py", line 392, in <module>
    visualizeCodeAndWrite(code_path=config.code_path, prefix=config.prefix, generateGT=False, save_path=config.save_path)
  File "/kaggle/working/codebook/VisualizeCodebook.py", line 359, in visualizeCodeAndWrite
    out_poses, out_code = visualize_code(config, model_path, save_path, prefix, code_source, normalize=True)
  File "/kaggle/working/codebook/VisualizeCodebook.py", line 130, in visualize_code
    model = nn.DataParallel(model, device_ids=[eval(i) for i in config.no_cuda])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 145, in __init__
    _check_balance(self.device_ids)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 25, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 678, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 678, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 659, in _get_device_attr
    return get_member(torch.cuda)
  File "/opt/conda/lib/python3.10/site-packages/torch/_utils.py", line 678, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "/opt/conda/lib/python3.10/site-packages/torch/cuda/__init__.py", line 398, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
```

**Comment by YoungSeng** [comment]
Sorry for the confusing code, the parameter `no_cuda` and `gpu` should be the same. I have fixed the complex code, see [train.py](https://github.com/YoungSeng/QPGesture/blob/5dae1b86876c1bedd79800d6a9f5040cf06794e4/codebook/train.py#L161), [VisualizeCodebook.py](https://github.com/YoungSeng/QPGesture/blob/5dae1b86876c1bedd79800d6a9f5040cf06794e4/codebook/VisualizeCodebook.py#L387), [PAE.py](https://github.com/YoungSeng/QPGesture/blob/5dae1b86876c1bedd79800d6a9f5040cf06794e4/codebook/PAE.py#L523) and [beat_data_to_lmdb.py](https://github.com/YoungSeng/QPGesture/blob/5dae1b86876c1bedd79800d6a9f5040cf06794e4/process/beat_data_to_lmdb.py#L310). Thank you.
